apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-development
spec:
  environment: development
  hostname: 172.17.0.1.xip.io
  readReplicaHostnames:
  - 172.17.0.1.xip.io
  password: password
  port: '3306'
  user: root
---
apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-production
spec:
  environment: production
  hostname: 172.17.0.1.xip.io
  readReplicaHostnames:
  - 172.17.0.1.xip.io
  password: password
  port: '3306'
  user: root